FROM python:3.10-slim
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y libpango-1.0-0 libpangoft2-1.0-0
RUN pip install --no-cache-dir -r requirements.txt
CMD gunicorn bot:app --bind 0.0.0.0:$PORT --workers 1